ecomerse/ecomerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),
    path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomerse/store/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name='store'

urlpatterns = [
    path('signup/',views.signup,name="signup"),
    path('login/',views.logine,name="login"),
    path('logout/',views.logoute,name="logout"),
    path('single_buy/',views.single_product,name="single_buy"),
    path('about/',views.about_us,name="about"),
    path('contact/',views.contact_us,name="contact"),
    path('', views.product_list, name='product_list'),
	path('cart/', views.view_cart, name='view_cart'),
	path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
	path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('forgot/',views.forgot_password,name="forgot"),
]

ecomerse/store/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


class Category(models.Model):
	name = models.CharField(max_length=100)
	
	def __str__(self):
		return self.name

class Product(models.Model):
	name = models.CharField(max_length=100)
	catogory = models.ForeignKey(Category, on_delete=models.CASCADE)
	description = models.TextField(null=True)
	price = models.DecimalField(max_digits=10, decimal_places=2)
	image = models.ImageField(upload_to='products/')

	def __str__(self):
		return self.name

class CartItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(default=0)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.quantity} x {self.product.name}'


# class CustomUser(AbstractUser):
#     pass


class CustomUser(AbstractUser):
    # ... other fields ...

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='customuser_set',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )

    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='customuser_set',
        blank=True,
        help_text='Specific permissions for this user.',
    )

ecomerse/store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from store.models import *


# Create your views here.

def index(request):
    return render(request,'index.html')

def single_product(request):
    return render(request,'single.html')

def about_us(request):
    return render(request,'about.html')

def contact_us(request):
    return render(request,'contact.html')

def signup(request):
    if request.method=="POST":
        first=request.POST.get('fname')
        second=request.POST.get('sname')
        n=' '
        username=first+n+second
        email=request.POST.get('email')
        password=request.POST.get('password')
        password1=request.POST.get('password1')
        if password == password1:
            if User.objects.filter(username=username,email=email,password=password).exists():
                messages.info(request,'username already exists')
                print('already have')
            else:
                user=User.objects.create_user(username,email,password)
                user.save()
                return redirect('store:login')
        else:
            print('wrong password')
    return render(request,'signup.html')

def logine(request):
    if request.method == 'POST':
        username = request.POST.get('name')
        password1 = request.POST.get('password')
        user=authenticate(username=username,password=password1)
        if user is not None:
            login(request,user)
            return redirect('store:product_list')
        else:
            messages.info(request,'user not exist')
            print('user not  exist')
            return redirect('store:login')
    return render(request,'login.html')


def logoute(request):
    logout(request)
    return redirect('store:product_list')
def product_list(request):
    
    products_female = Product.objects.filter(catogory=Category.objects.get(id=1))
    products_male = Product.objects.filter(catogory=Category.objects.get(id=2))
    products_kids = Product.objects.filter(catogory=Category.objects.get(id=3))
    return render(request, 'index.html', {'mproducts': products_male,'fproducts':products_female,'cproducts':products_kids})

def view_cart(request):
	cart_items = CartItem.objects.filter(user=request.user)
	total_price = sum(item.product.price * item.quantity for item in cart_items)
	return render(request, 'cart.html', {'cart_items': cart_items, 'total_price': total_price})

def add_to_cart(request, product_id):
	product = Product.objects.get(id=product_id)
	cart_item, created = CartItem.objects.get_or_create(product=product, 
													user=request.user)
	cart_item.quantity += 1
	cart_item.save()
	return redirect('store:view_cart')

# def remove_from_cart(request, item_id):
# 	cart_item = CartItem.objects.get(id=item_id)
# 	cart_item.delete()
# 	return redirect('store:view_cart')

def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('store:view_cart')


def forgot_password(request):
     return render(request,'forgot.html')


class CustomPasswordResetView(PasswordResetView):
    template_name = 'password_reset.html'
    success_url = reverse_lazy('password_reset_done')

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_confirm.html'
    success_url = reverse_lazy('password_reset_complete')

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'

ecomerse/templates/cart.html
{% load static %}

<html lang="en">

<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Hexashop_Cart</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static '/assets/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static '/assets/css/templatemo-hexashop.css' %}">

    <link rel="stylesheet" href="{% static '/assets/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static '/assets/css/lightbox.css' %}">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->

    

</head>

<body>
	<header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="{% static '/assets/images/logo.png' %}">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="#men">Men's</a></li>
                            <li class="scroll-to-section"><a href="#women">Women's</a></li>
                            <li class="scroll-to-section"><a href="#kids">Kid's</a></li>
                            <li class="submenu">
                                <a href="javascript:;">Pages</a>
                                <ul>
                                    <li><a href="{% url 'store:about' %}">About Us</a></li>
                                    <!-- <li><a href="products.html">Products</a></li> -->
                                    <!-- <li><a href="single-product.html">Single Product</a></li> -->
                                    <li><a href="{% url 'store:contact' %}">Contact Us</a></li>
                                </ul>
                            </li>

                            <li class="scroll-to-section"><a href="#explore">Explore</a></li>
                            {% if user.is_authenticated %}

                            <li class="scroll-to-section"><a href="{% url 'store:logout' %}">Logout</a></li>
                            {% else %}
                            <li class="scroll-to-section"><a href="{% url 'store:signup' %}">Sign Up</a></li>
                            <li class="scroll-to-section"><a href="{% url 'store:login' %}">Login</a></li>
                            {% endif %}

                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
	<section class="our-services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <h2>Your CART</h2>
                        <span>here you can purchase your items from your cart</span>
                    </div>
                </div>
				{% for item in cart_items %}
                <div class="col-lg-4">
                    <div class="service-item">
                        <h4>{{ item.product.name }} ({{ item.quantity }})</h4>
                        <!-- <p>Lorem ipsum dolor sit amet, consecteturti adipiscing elit, sed do eiusmod temp incididunt ut labore, et dolore quis ipsum suspend.</p> -->
                        <span>${{ item.product.price }}</span>
						<img src="{{ item.product.image.url }}" alt="">
                        <form action="{% url 'store:remove_from_cart' item_id=item.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-secondary">Remove</button>
                        </form>
                    </div>
                </div>
				{% empty %}
					<p>Your cart is empty.</p>
                {% endfor %}
                
            </div>
        </div>
    </section>

	<div class="container">
		<div class="row">
			<div class="col">
				<h4>Total Price: ${{ total_price }}</h4>
			</div>
			<div class="col">
				<label for="">to Explore :</label><a href="{% url 'store:product_list' %}">Continue Shopping</a>
			</div>
		</div>
		
	</div>
	



	<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="{% static '/assets/images/white-logo.png' %}" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                            <li><a href="#">hexashop@company.com</a></li>
                            <li><a href="#">010-020-0340</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>Shopping &amp; Categories</h4>
                    <ul>
                        <li><a href="#">Men’s Shopping</a></li>
                        <li><a href="#">Women’s Shopping</a></li>
                        <li><a href="#">Kid's Shopping</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Homepage</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Help &amp; Information</h4>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">FAQ's</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Tracking ID</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2023 HexaShop Co., Ltd. All Rights Reserved. 
                        
                        <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">Swetha Elsa John</a></p>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    
</body>

</html>

ecomerse/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Hexashop - Contact Page</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static '/assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static '/assets/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static '/assets/css/templatemo-hexashop.css' %}">

    <link rel="stylesheet" href="{% static '/assets/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static '/assets/css/lightbox.css' %}">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->
    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="{% static '/assets/images/logo.png' %}">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading about-page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Contact Us</h2>
                        <span>Awesome, collections &amp; trendy fashions</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->

    <!-- ***** Contact Area Starts ***** -->
    <div class="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div id="map">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d90186.37207676383!2d-80.13495239500924!3d25.9317678710111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d9ad1877e4a82d%3A0xa891714787d1fb5e!2sPier%20Park!5e1!3m2!1sen!2sth!4v1637512439384!5m2!1sen!2sth" width="100%" height="400px" frameborder="0" style="border:0" allowfullscreen></iframe>
                      <!-- You can simply copy and paste "Embed a map" code from Google Maps for any location. -->
                      
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="section-heading">
                        <h2>Say Hello. Don't Be Shy!</h2>
                        <span>Details to details is what makes Hexashop different from the other themes.</span>
                    </div>
                    <form id="contact" action="" method="post">
                        <div class="row">
                          <div class="col-lg-6">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-6">
                            <fieldset>
                              <input name="email" type="text" id="email" placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6" id="message" placeholder="Your message" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-dark-button"><i class="fa fa-paper-plane"></i></button>
                          </div>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Contact Area Ends ***** -->

    <!-- ***** Subscribe Area Starts ***** -->
    <div class="subscribe">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-heading">
                        <h2>By Subscribing To Our Newsletter You Can Get 30% Off</h2>
                        <span>Details to details is what makes Hexashop different from the other themes.</span>
                    </div>
                    <form id="subscribe" action="" method="get">
                        <div class="row">
                          <div class="col-lg-5">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your Name" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-5">
                            <fieldset>
                              <input name="email" type="text" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your Email Address" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-2">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-dark-button"><i class="fa fa-paper-plane"></i></button>
                            </fieldset>
                          </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="row">
                        <div class="col-6">
                            <ul>
                                <li>Store Location:<br><span>Sunny Isles Beach, FL 33160, United States</span></li>
                                <li>Phone:<br><span>010-020-0340</span></li>
                                <li>Office Location:<br><span>North Miami Beach</span></li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <ul>
                                <li>Work Hours:<br><span>07:30 AM - 9:30 PM Daily</span></li>
                                <li>Email:<br><span>info@company.com</span></li>
                                <li>Social Media:<br><span><a href="#">Facebook</a>, <a href="#">Instagram</a>, <a href="#">Behance</a>, <a href="#">Linkedin</a></span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Subscribe Area Ends ***** -->

    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="{% static '/assets/images/white-logo.png' %}" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                            <li><a href="#">hexashop@company.com</a></li>
                            <li><a href="#">010-020-0340</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>Shopping &amp; Categories</h4>
                    <ul>
                        <li><a href="#">Men’s Shopping</a></li>
                        <li><a href="#">Women’s Shopping</a></li>
                        <li><a href="#">Kid's Shopping</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Homepage</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Help &amp; Information</h4>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">FAQ's</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Tracking ID</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2023 HexaShop Co., Ltd. All Rights Reserved. 
                        
                        <br>Design: <a href="https://templatemo.com" target="_parent" title="">Swetha Elsa John</a></p>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="{% static '/assets/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static '/assets/js/popper.js' %}"></script>
    <script src="{% static '/assets/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static '/assets/js/owl-carousel.js' %}"></script>
    <script src="{% static '/assets/js/accordions.js' %}"></script>
    <script src="{% static '/assets/js/datepicker.js' %}"></script>
    <script src="{% static '/assets/js/scrollreveal.min.js' %}"></script>
    <script src="{% static '/assets/js/waypoints.min.js' %}"></script>
    <script src="{% static '/assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static '/assets/js/imgfix.min.js' %}"></script> 
    <script src="{% static '/assets/js/slick.js' %}"></script> 
    <script src="{% static '/assets/js/lightbox.js' %}"></script> 
    <script src="{% static '/assets/js/isotope.js' %}"></script> 
    
    <!-- Global Init -->
    <script src="{% static '/assets/js/custom.js' %}"></script>

    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);
                
            });
        });

    </script>

  </body>

</html>

ecomerse/templates/forgot.html
{% extends 'index.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block css %}
  <style>
    @import 'https://static.stayjapan.com/assets/dashboard/application-33c1a06b7784b53cd746d479718b6295c0fcefebb696e78dcee7c68efc92fada.css';


 Horizontal container

.horizontal-container {
  margin: 0 auto;
  width: 100%;
  
  @media(min-width: 768px) {
    width: 500px;
  }
  
  
 
  
  /* Create circle */
  @mixin drawCircle {
    background-color: white;
    border-radius: 50%; 
    border: 2px solid #ccc;
    color: #ccc;
    display: block;
    height: 20px;
    line-height: 18px;
    margin: 0 auto;
    text-align: center;
    width: 20px;
  }

  /* Create line */
  @mixin drawLine {
    background-color: #e5e5e5;
    content: '';
    height: 3px;
    left: -50%;
    transform: translateX(50%);
    position: absolute;
    top: 9px;
    width: 100%;
    z-index: -1;
  }

    /* Custom progress bar */
  .progress-bar-container {
    position: relative;

    .custom-progress-bar {
      counter-reset: step; /* Initial step: 0 */
      padding-left: 0;
    }

    .custom-progress-bar li {
      float: left;
      font-size: 12px;
      list-style: none;
      position: relative;
      text-align: center;
      text-transform: uppercase;
      width: 50%;

      &:before {
        @include drawCircle;
        content: counter(step);
        counter-increment: step;
      }

      &:after {
        @include drawLine;
      }

      &:last-child {
        &:before {
          display: none;
        }
        &:after {
          display: none;
        }
      }

      &.active {
        &:before {
          border-color: red;
          color: red;
        }    
      }

      &.finished {
        &:before {
          background-color: red;
          border-color: red;
          color: #fff;
          content: "\2713"
        }
      }
    }

    .custom-progress-line {
      height: 3px;
      position: absolute;
      content: '';
      top: 9px;
      left: 0;
      width: auto;
      background-color: red;
    }
  }
 
  
   Horizontal form
  
  .horizontal-form-box {
    background-color: #fff;
    border: 1px solid #e5e5e5;
    height: 466px;
    padding: 30px;
    
    .horizontal-info-container {   
      img {
        height: 75px;
        margin-bottom: 20px; 
      }

      .horizontal-heading {
        color: #000;
        font-size: 22px; 
        font-weight: bold; 
        text-transform: capitalize;
      }

      .horizontal-subtitle {
        letter-spacing: 1px;
        margin-bottom: 20px;
        text-align: left;
      }
    }
  
    .horizontal-form {
      label,
      button {
        text-transform: capitalize;
      }

      label {
        color: #000;
        font-weight: normal;
      }
    }
  }
}
  </style>
  {% endblock css %}
  {% block body %}

{% if page == 'register' %}
<div class="container" style="margin-top: 40px;">
  <div class="row">
    <div class="col-sm-12">
      <div class="horizontal-container">
        <div class="progress-bar-container">
          <div class="custom-progress-line" style="width: 25%;"></div>
          <ul class="custom-progress-bar clearfix">
            <li class="active">Reset password</li>
            <li>Login</li>
            <li class="finish-line"></li>
          </ul>
        </div>
        <div class="horizontal-form-box">
          <div class="horizontal-info-container text-center">
            <img src="https://static.stayjapan.com/assets/top/icon/values-7dd5c8966d7a6bf57dc4bcd11b2156e82a4fd0da94a26aecb560b6949efad2be.svg" />
            <p class="horizontal-heading">Reset your password</p>
            <p class="horizontal-subtitle">Your password needs to be at least 8 characters.</p>
          </div>
          <form class="horizontal-form" method="post" action="{% url 'register' %}">
            {% csrf_token %}
            <div class="o3-form-group">
              <label for="new_password">New password</label>
              <input type="password" class="o3-form-control o3-input-lg" id="new_password">
            </div>
            <div class="o3-form-group">
              <label for="confirm_password">Confirm new password</label>
              <input type="password" class="o3-form-control o3-input-lg" id="confirm_password">
            </div>
            <button class="o3-btn o3-btn-primary o3-btn-block">Set new password</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
  {% endblock %}
</body>
</html>